### ISSUE TITLE
0.5.x should have the direction default back again to right.

### ISSUE THREAD

**Issue by lejoe** [meodai/sensible#20]
I'm fine with the change but this is a breaking change.
All projects we delivered with 0.5.x will be broken if tried to be built again.

I would advise to revert the change in 0.5.5 and make a 0.6.0 that introduces this.

**Comment by meodai** [comment]
since the project is under 1.0 this will happen more often. Maybe we should use the exact version number in the bower file then. PS: I wonder what broke, since the grid should be self-contained

**Comment by lejoe** [comment]
The girds are not aligned anymore when left aligned.
![image](https://cloud.githubusercontent.com/assets/1759/9574718/8a50b20e-4fc9-11e5-8ed5-5f820c579906.png)


You're right with both of your point but the pragmatic result is that with this change you can impact of the display of old projects. Thus my request for a simple version change

**Comment by meodai** [comment]
@lejoe did you overwrite the width or the margin of the container somewhere?

**Comment by lejoe** [comment]
Yeah, ok, found the bug, was again because of this damn fieldset.
officially became my most hated HTML tag.
